CommercialSite/CommercialSite.Web.UI/Areas/User/Controllers/OrderController.cs
using AutoMapper;
using CommercialSite.Common.DTOs.Order;
using CommercialSite.Web.UI.APIs;
using CommercialSite.Web.UI.Areas.User.Models.OrderInfoViewModels;
using CommercialSite.Web.UI.Areas.User.Models.OrderViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace CommercialSite.Web.UI.Areas.User.Controllers
{
    [Area("User"), Authorize]
    public class OrderController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IOrderApi _orderApi;
        private readonly IOrderInfoApi _orderInfoApi;
        private readonly IUserApi _userApi;
        private readonly IProductApi _productApi;
        private readonly IMapper _mapper;
        public OrderController(
            IWebHostEnvironment env,
            IOrderApi orderApi,
            IOrderInfoApi orderInfoApi,
            IProductApi productApi,
            IUserApi userApi,
            IMapper mapper)
        {
            _env = env;
            _orderApi = orderApi;
            _orderInfoApi = orderInfoApi;
            _productApi = productApi;
            _userApi = userApi;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {

            var userId = JsonConvert.DeserializeObject<Guid>(HttpContext.Session.GetString("UserId"));
            List<OrderViewModel> list = new List<OrderViewModel>();
            var listResult = await _orderApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<OrderViewModel>>(listResult.Content.ResultData.Where(x=>x.UserId == userId));
            var a = list.GroupBy(x => x.OrderInfoId).ToList();
            List<OrderViewModel> listGroupBy = new List<OrderViewModel>();
            foreach (var item in a)
            {
                foreach (var item1 in item)
                {
                    listGroupBy.Add(item1);
                }
            }
            return View(listGroupBy);
        }

        [HttpGet]
        public async Task<IActionResult> Insert()
        {
            List<UserViewModel> list = new List<UserViewModel>();
            var listResult = await _userApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<UserViewModel>>(listResult.Content.ResultData);
            ViewBag.Users = new SelectList(list, "Id", "FirstName");

            List<ProductViewModel> listProduct = new List<ProductViewModel>();
            var listProductResult = await _userApi.List();
            if (listProductResult.IsSuccessStatusCode && listProductResult.Content.IsSuccess && listProductResult.Content.ResultData.Any())
                listProduct = _mapper.Map<List<ProductViewModel>>(listProductResult.Content.ResultData);
            ViewBag.Products = new SelectList(listProduct, "Id", "ProductName");

            List<OrderInfoViewModel> listOrderInfo = new List<OrderInfoViewModel>();
            var listOrderInfoResult = await _userApi.List();
            if (listOrderInfoResult.IsSuccessStatusCode && listOrderInfoResult.Content.IsSuccess && listOrderInfoResult.Content.ResultData.Any())
                listOrderInfo = _mapper.Map<List<OrderInfoViewModel>>(listOrderInfoResult.Content.ResultData);
            ViewBag.OrderInfos = new SelectList(listOrderInfo, "Id", "ShippingFirstName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Insert(CreateOrderViewModel item, List<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                var insertResult = await _orderApi.Post(_mapper.Map<OrderRequest>(item));
                if (insertResult.IsSuccessStatusCode && insertResult.Content.IsSuccess && insertResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";

            }
            else
                TempData["Message"] = "İşlem başarısız oldu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            List<UserViewModel> list = new List<UserViewModel>();
            var listResult = await _userApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<UserViewModel>>(listResult.Content.ResultData);
            ViewBag.Users = new SelectList(list, "Id", "FirstName");

            List<ProductViewModel> listProduct = new List<ProductViewModel>();
            var listProductResult = await _userApi.List();
            if (listProductResult.IsSuccessStatusCode && listProductResult.Content.IsSuccess && listProductResult.Content.ResultData.Any())
                listProduct = _mapper.Map<List<ProductViewModel>>(listProductResult.Content.ResultData);
            ViewBag.Products = new SelectList(listProduct, "Id", "ProductName");

            List<OrderInfoViewModel> listOrderInfo = new List<OrderInfoViewModel>();
            var listOrderInfoResult = await _userApi.List();
            if (listOrderInfoResult.IsSuccessStatusCode && listOrderInfoResult.Content.IsSuccess && listOrderInfoResult.Content.ResultData.Any())
                listOrderInfo = _mapper.Map<List<OrderInfoViewModel>>(listOrderInfoResult.Content.ResultData);
            ViewBag.OrderInfos = new SelectList(listOrderInfo, "Id", "ShippingFirstName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateOrderViewModel item)
        {
            if (ModelState.IsValid)
            {

                var updateResult = await _orderApi.Put(item.Id, _mapper.Map<OrderRequest>(item));
                if (updateResult.IsSuccessStatusCode && updateResult.Content.IsSuccess && updateResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            }
            else
                TempData["Message"] = "İşlem başarısız oldu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            return View(item);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var deleteResult = await _orderApi.Delete(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Activate(Guid id)
        {
            var deleteResult = await _orderApi.Activate(id);
            return RedirectToAction("Index");
        }
    }
}

CommercialSite/CommercialSite.Web.UI/Controllers/ProductListController.cs
using AutoMapper;
using CommercialSite.Web.UI.APIs;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductPropertyViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialSite.Web.UI.Controllers
{
    public class ProductListController : Controller
    {
        private readonly IProductApi _productApi;
        private readonly IProductPropertyApi _productPropertyApi;
        private readonly IMapper _mapper;

        public ProductListController(
            IProductApi productApi,
            IProductPropertyApi productPropertyApi,
            IMapper mapper)
        {
            _productApi = productApi;
            _productPropertyApi = productPropertyApi;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index(string name)
        {
            List<ProductViewModel> listProduct = new List<ProductViewModel>();
            var listProductResult = await _productApi.List();
            if (listProductResult.IsSuccessStatusCode && listProductResult.Content.IsSuccess && listProductResult.Content.ResultData.Where(x=>x.Brand.BrandName.ToLower() == name.ToLower()).Any())
                listProduct = _mapper.Map<List<ProductViewModel>>(listProductResult.Content.ResultData.Where(x=>x.Brand.BrandName.ToLower() == name.ToLower()).ToList());

            else if (listProductResult.IsSuccessStatusCode && listProductResult.Content.IsSuccess && listProductResult.Content.ResultData.Where(x => x.Category.CategoryName.ToLower() == name.ToLower()).Any())
                listProduct = _mapper.Map<List<ProductViewModel>>(listProductResult.Content.ResultData.Where(x => x.Category.CategoryName.ToLower() == name.ToLower()).ToList());

            return View(listProduct);
        }
    }
}

CommercialSite/CommercialSite.Web.UI/Controllers/SignInController.cs
using AutoMapper;
using CommercialSite.Common.DTOs.User;
using CommercialSite.Web.UI.APIs;
using CommercialSite.Web.UI.Areas.Admin.Models.UserViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialSite.Web.UI.Controllers
{
    public class SignInController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IUserApi _userApi;
        private readonly IMapper _mapper;
        public SignInController(
            IWebHostEnvironment env,
            IUserApi userApi,
            IMapper mapper)
        {
            _env = env;
            _userApi = userApi;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Register(CreateUserViewModel item)
        {
            UpdateUserViewModel model = new UpdateUserViewModel();
            var updateModelResultList = await _userApi.List();
            var list = updateModelResultList.Content.ResultData.Where(x => x.Email == item.Email).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (list == null)
                {
                    var insertResult = await _userApi.Post(_mapper.Map<UserRequest>(item));
                    if (insertResult.IsSuccessStatusCode && insertResult.Content.IsSuccess && insertResult?.Content?.ResultData != null)
                        return RedirectToAction("Login", "Account");
                    else
                        TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
                }
                else
                {
                    TempData["Message"] = "Böyle bir email hesabı zaten vardır...";
                }
                
            }
            else
                TempData["Message"] = "İşlem başarısız oldu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";

            return View("Index");
        }
    }
}

CommercialSite/CommercialSite.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TEKNOHAVUZ</title>
    <link href="~/Content/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/my-css/Footer.css" rel="stylesheet" />
    <link href="~/Content/my-css/Header.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark" id="mainNavbar">
            @Html.ActionLink("TEKNO HAVUZ", "Index", "Home", new { id = "" }, new { @class = "offset-md-2 navbar-brand col-lg-2", id = "titleMain" });
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                @using (Html.BeginForm("Index", "ProductList", FormMethod.Get, new Dictionary<string, object>()
                                                                                                        {
                               { "class" ,"form-inline my-2 my-lg-3"},
                               { "id" , "mainSearch" }
                           }))
                {
                    <input class="form-control mr-sm-1" id="Search" name="name" type="text" placeholder="Search">
                    <button class="btn btn-dark my-2 my-sm-0" type="submit"><span class="bi-search"></span></button>
                }

                @if (string.IsNullOrEmpty(User.Identity.Name))
                {
                    <ul class="offset-md-2 navbar-nav mr-auto" id="mainListUnlogin">
                        <li class="nav nav-item" id="animeNavbarLink">
                            <a asp-controller="ShoppingCart" asp-action="List" class="nav-link"><span class="bi-cart-dash">Sepet</span></a>
                        </li>

                        <li class="nav nav-item" id="animeNavbarLink">

                            <a class="nav-link" asp-controller="Account" asp-action="Login" asp-area=""> <span class="bi-person-fill">Giriş Yap</span></a>
                        </li>
                        <li class="nav nav-item" id="animeNavbarLink">
                            <a class="nav-link" asp-controller="SignIn" asp-action="Register" asp-area=""> <span class="bi-person-plus-fill">Kayıt Ol</span></a>
                        </li>
                    </ul>
                }
                else if (User.Identity.Name != "Admin")
                {

                    <div class="dropdown">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            Hesap
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-controller="AccountInfo" asp-action="InfoPanel" asp-area="User">Hesap Bilgim</a>
                            <a class="dropdown-item" asp-controller="Order" asp-action="Index" asp-area="User">Siparişlerim</a>
                            <a class="dropdown-item" asp-controller="FavoriteProduct" asp-action="Index" asp-area="User">Favori Ürünlerim</a>
                        </div>
                    </div>
                    <ul class="offset-md-2 navbar-nav mr-auto" id="mainListUnlogin">
                        <li class="nav nav-item" id="animeNavbarLink">
                            <a asp-controller="ShoppingCart" asp-action="List" class="nav-link"><span class="bi-cart-dash">Sepet</span></a>
                        </li>
                        <li class="nav nav-item" id="animeNavbarLink">
                            <a class="nav-link" asp-controller="Account" asp-action="Logout" title=""><span class="bi-power">Çıkış</span></a>
                        </li>
                    </ul>

                }
                else
                {
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    Hesap
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-controller="AccountInfo" asp-action="InfoPanel" asp-area="User">Hesap Bilgim</a>
                    <a class="dropdown-item" asp-controller="Order" asp-action="Index" asp-area="User">Siparişlerim</a>
                    <a class="dropdown-item" asp-controller="FavoriteProduct" asp-action="Index" asp-area="User">Favori Ürünlerim</a>
                </div>
            </div>

                    <ul class="offset-md-2 navbar-nav mr-auto" id="mainListUnlogin">
                        <li class="nav nav-item" id="animeNavbarLink">
                            <a asp-controller="ShoppingCart" asp-action="List" class="nav-link"><span class="bi-cart-dash">Sepet</span></a>
                        </li>
                        <li class="nav nav-item" id="animeNavbarLink"><a class="nav-link" asp-controller="Home" asp-action="Index" asp-area="Admin" title=""><span class="bi-file-person">Yönetici</span></a></li>
                        <li class="nav nav-item" id="animeNavbarLink"><a class="nav-link" asp-controller="Account" asp-action="Logout" title=""><span class="bi-power">Çıkış</span></a></li>
                    </ul>

                }

                @*<ul class="offset-md-2 navbar-nav mr-auto" id="mainListUnlogin">
            <li class="nav nav-item" id="animeNavbarLink">
                <a asp-controller="ShoppingCart" asp-action="List" class="nav-link"><span class="bi-cart-dash">Sepet</span></a>
            </li>
            @if (string.IsNullOrEmpty(User.Identity.Name))
            {
                <li class="nav nav-item" id="animeNavbarLink">

                    <a class="nav-link" asp-controller="Account" asp-action="Login" asp-area=""> <span class="bi-person-fill">Giriş Yap</span></a>
                </li>
                <li class="nav nav-item" id="animeNavbarLink">
                    <a class="nav-link" asp-controller="SignIn" asp-action="Register" asp-area=""> <span class="bi-person-plus-fill">Kayıt Ol</span></a>
                </li>
            }
            else if (User.Identity.Name != "Admin")
            {
                <li class="nav nav-item" id="animeNavbarLink">
                    <a class="nav-link" asp-controller="Account" asp-action="Logout" title=""><span class="bi-power">Çıkış</span></a>
                </li>
            }
            else
            {
                <li class="nav nav-item" id="animeNavbarLink"><a class="nav-link" asp-controller="Home" asp-action="Index" asp-area="Admin" title=""><span class="bi-file-person">Yönetici</span></a></li>
                <li class="nav nav-item" id="animeNavbarLink"><a class="nav-link" asp-controller="Account" asp-action="Logout" title=""><span class="bi-power">Çıkış</span></a></li>
            }
        </ul>*@
            </div>

        </nav>

        <div class="row" id="row">
            <div class="col-lg-3" id="row1">

            </div>
            <div class="col-lg-3" id="row2">

            </div>
            <div class="col-lg-3" id="row3">

            </div>
            <div class="col-lg-3" id="row4">

            </div>
        </div>
    </header>

    <main>
        @RenderBody()
    </main>
    <div class="container-fluid justify-content-center px-0 ">

        <footer>
            <div class="row justify-content-around mb-0 pt-5 mx-4">
                <div class="col-xl-2 col-md-4 order-xl-1 order-4 mr-xl-0 my-auto">
                    <ul class="list-unstyled mt-md-3 mt-5">
                        <li>Social Media</li>
                        <li class="social"> <span> <i class="bi bi-facebook" aria-hidden="true"></i></span> <span> <i class="bi bi-instagram" aria-hidden="true"></i> </span> <span> <i class="bi bi-twitter" aria-hidden="true"></i> </span> </li>
                    </ul>
                    <ul class="list-unstyled my-xl-4 my-md-3">
                        <li>Copyright</li>
                        <li>&#9400; Nutrition 2019</li>
                    </ul>
                </div>
                <div class="col-xl-2 col-md-3 pt-4 order-1">
                    <ul class="list-unstyled">
                        <li class="mt-md-0 mt-4">Our Solution</li>
                        <li>Intergrated Security </li>
                        <li>Core Features</li>
                        <li>Product Features</li>
                        <li>Pricing</li>
                    </ul>
                </div>
                <div class="col-xl-2 col-md-3 pt-4 order-2">
                    <ul class="list-unstyled">
                        <li class="mt-md-0 mt-4">Your needs</li>
                        <li>Intergrated Security </li>
                        <li>Core Features</li>
                        <li>Product Features</li>
                        <li>Pricing</li>
                    </ul>
                </div>
                <div class="col-xl-auto col-md-3 pt-4 my-sm-0 order-md-3 order-sm-1 ">
                    <ul class="list-unstyled">
                        <li class="mt-md-0 mt-4">Offer</li>
                        <li>Intergrated Security </li>
                        <li>Core Features</li>
                        <li>Product Features</li>
                        <li>Pricing</li>
                    </ul>
                </div>
                <div class="col-xl-auto col-md-6 col-12 pt-4 my-sm-0 order-6 ">
                    <div class="form-group "><label for="email" class="mb-3"><b>Subscribe to our newsletter and Get 10% off</b></label><input type="email" class="form-control form-control-lg" placeholder="Enter email" id="email"></div><button id="footerSubmit" type="button" class="btn btn-primary btn-lg btn-block my-2 Subscribe mt-4 mb-3">Subscribe</button>
                </div>
            </div>
            <div class="row justify-content-center px-3 py-3 pt-5">
                <div class="col text-center">
                    <p class="mb-0">*These statement have not evaluated by the Food and Drug Addministrations.</p>
                    <p>This product is not intented to diagonse,treat,cure, or prevent any disease.</p>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/Content/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/Content/jquery/jquery.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>