CommercialSite/CommercialSite.Web.UI/Areas/Admin/Models/ProductCommentViewModels/ProductCommentViewModel.cs
using CommercialSite.Common.Enums;
using CommercialSite.Web.UI.Areas.Admin.Models.CommentReactionViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductDetailViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CommercialSite.Web.UI.Areas.Admin.Models.ProductCommentViewModels
{
    public class ProductCommentViewModel
    {
        public ProductCommentViewModel()
        {
            ProductDetails = new HashSet<ProductDetailViewModel>();
            CommentReactions = new HashSet<CommentReactionViewModel>();
        }
        public Guid Id { get; set; }
        [Required]
        public Guid ProductId { get; set; }
        public ProductViewModel Product { get; set; }
        public string Comment { get; set; }
        [Required]
        public string Rate { get; set; }
        public int? ThumbsUp { get; set; }
        public int? ThumbDown { get; set; }
        public Status Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public ICollection<ProductDetailViewModel> ProductDetails { get; set; }
        public ICollection<CommentReactionViewModel> CommentReactions { get; set; }
    }
}

CommercialSite/CommercialSite.Web.UI/Areas/Admin/Controllers/ProductCommentController.cs
using AutoMapper;
using CommercialSite.Common.DTOs.ProductComment;
using CommercialSite.Web.UI.APIs;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductCommentViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialSite.Web.UI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class ProductCommentController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IProductCommentApi _productCommentApi;
        private readonly IProductApi _productApi;
        private readonly IMapper _mapper;
        public ProductCommentController(
            IWebHostEnvironment env,
            IProductCommentApi productCommentApi,
            IProductApi productApi,
            IMapper mapper)
        {
            _env = env;
            _productCommentApi = productCommentApi;
            _productApi = productApi;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<ProductCommentViewModel> list = new List<ProductCommentViewModel>();
            var listResult = await _productCommentApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductCommentViewModel>>(listResult.Content.ResultData);
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> Insert()
        {
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            ViewBag.Products = new SelectList(list, "Id", "ProductName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Insert(CreateProductCommentViewModel item, List<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                var insertResult = await _productCommentApi.Post(_mapper.Map<ProductCommentRequest>(item));
                if (insertResult.IsSuccessStatusCode && insertResult.Content.IsSuccess && insertResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";

            }
            else
                TempData["Message"] = "İşlem başarısız oldu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            ViewBag.Products = new SelectList(list, "Id", "ProductName");

            UpdateProductCommentViewModel model = new UpdateProductCommentViewModel();
            var updateModelResult = await _productCommentApi.Get(id);
            if (updateModelResult.IsSuccessStatusCode && updateModelResult.Content.IsSuccess && updateModelResult?.Content?.ResultData != null)
                model = _mapper.Map<UpdateProductCommentViewModel>(updateModelResult?.Content?.ResultData);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateProductCommentViewModel item)
        {
            if (ModelState.IsValid)
            {

                var updateResult = await _productCommentApi.Put(item.Id, _mapper.Map<ProductCommentRequest>(item));
                if (updateResult.IsSuccessStatusCode && updateResult.Content.IsSuccess && updateResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            }
            else
                TempData["Message"] = "İşlem başarısız oldu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            return View(item);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var deleteResult = await _productCommentApi.Delete(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Activate(Guid id)
        {
            var deleteResult = await _productCommentApi.Activate(id);
            return RedirectToAction("Index");
        }
    }
}

CommercialSite/CommercialSite.Web.UI/Areas/Admin/Views/ProductComment/Index.cshtml
@model List<ProductCommentViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_YöneticiLayout.cshtml";
}

<div class="content-body">
    <div class="row justify-content-between align-items-center mb-10">
        <div class="col-12 col-lg-auto mb-20">
            <div class="page-heading">
                <h3 class="title">List <span>/ ProductComments</span></h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-30">
            <div class="box">
                <div class="box-head">
                    <a asp-controller="ProductComment" asp-action="Insert" class="btn btn-primary">Yeni Kayıt</a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered data-table data-table-default">
                        <thead>
                            <tr>
                                <th>Comment</th>
                                <th>Rate</th>
                                <th>Product Name</th>
                                <th>Status</th>
                                <th>####</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (ProductCommentViewModel item in Model)
                            {
                            <tr>
                                @if (item.Comment.Length > 100)
                                {
                                    <td>@item.Comment.Substring(0, 100)...</td>
                                }
                                else
                                {
                                    <td>@item.Comment</td>
                                }
                                <td>@item.Rate</td>
                                <td><partial name="PartialViews/_StatusPartial" model="item.Status" /></td>
                                <td>
                                    <a asp-controller="ProductComment" asp-action="Activate" asp-route-id="@item.Id" class="btn">Activate</a>
                                    <a asp-controller="ProductComment" asp-action="Update" asp-route-id="@item.Id" class="btn">Update</a>
                                    <a asp-controller="ProductComment" asp-action="Delete" asp-route-id="@item.Id" class="btn">Delete</a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/admin/assets/js/plugins/datatables/datatables.min.js"></script>
    <script src="~/admin/assets/js/plugins/datatables/datatables.active.js"></script>
}

CommercialSite/CommercialSite.Web.UI/Areas/Admin/Views/ProductComment/Insert.cshtml
@model CreateProductCommentViewModel
@{
    ViewData["Title"] = "Insert";
    Layout = "~/Areas/Admin/Views/Shared/_YöneticiLayout.cshtml";
}

<div class="content-body">
    <div class="row justify-content-between align-items-center mb-10">
        <div class="col-12 col-lg-auto mb-20">
            <div class="page-heading">
                <h3>Blog <span>/ Add</span></h3>
            </div>
        </div>
    </div>
    <div class="add-edit-product-wrap col-12">
        <div class="add-edit-product-form">
            <form asp-controller="ProductComment" asp-action="Insert" method="post" enctype="multipart/form-data">
                <h4 class="title">About ProductComment</h4>
                <div class="row">
                    <div class="col-lg-12 col-12 mb-30">
                        <input asp-for="Comment" class="form-control" type="text" placeholder="Comment *">
                    </div>
                    <br />
                    <div class="col-lg-12 col-12 mb-30">
                        <input asp-for="Rate" class="form-control" type="text" placeholder="Rate *">
                    </div>
                    <br />
                    <div class="col-lg-12 col-12 mb-30">
                        <select asp-for="ProductId" asp-items="@ViewBag.Products" class="form-control">
                            <option>Please select Product..</option>
                        </select>
                    </div>
                    <br />
                </div>
                <div class="row">
                    <div class="d-flex flex-wrap justify-content-end col mbn-10">
                        <button class="button button-outline button-primary mb-10 ml-10 mr-0">Save</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["Message"]
        </div>
    }
</div>

@section scripts{
    <script src="~/admin/assets/js/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="~/admin/assets/js/plugins/summernote/summernote.active.js"></script>
    <script src="~/admin/assets/js/plugins/quill/quill.min.js"></script>
    <script src="~/admin/assets/js/plugins/quill/quill.active.js"></script>
}

CommercialSite/CommercialSite.Web.UI/Areas/Admin/Views/ProductComment/Update.cshtml
@model UpdateProductCommentViewModel

@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_YöneticiLayout.cshtml";
}

<div class="content-body">
    <div class="row justify-content-between align-items-center mb-10">
        <div class="col-12 col-lg-auto mb-20">
            <div class="page-heading">
                <h3>Blog <span>/ Add</span></h3>
            </div>
        </div>
    </div>
    <div class="add-edit-product-wrap col-12">
        <div class="add-edit-product-form">
            <form asp-controller="ProductComment" asp-action="Update" method="post">
                <input type="hidden" asp-for="Id" />
                <h4 class="title">About ProductComment</h4>
                <div class="row">
                    <div class="col-lg-12 col-12 mb-30">
                        <input asp-for="Comment" class="form-control" type="text" placeholder="Title *">
                    </div>
                    <br />
                    <div class="col-lg-12 col-12 mb-30">
                        <input asp-for="Rate" class="form-control" type="text" placeholder="Tags *">
                    </div>
                    <br />
                    <div class="col-lg-12 col-12 mb-30">
                        <select asp-for="ProductId" asp-items="@ViewBag.Products" class="form-control">
                            <option>Please select Product..</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="d-flex flex-wrap justify-content-end col mbn-10">
                        <button class="button button-outline button-primary mb-10 ml-10 mr-0">Save</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["Message"]
        </div>
    }
</div>

@section scripts{
    <script src="~/admin/assets/js/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="~/admin/assets/js/plugins/summernote/summernote.active.js"></script>
    <script src="~/admin/assets/js/plugins/quill/quill.min.js"></script>
    <script src="~/admin/assets/js/plugins/quill/quill.active.js"></script>
}