CommercialSite/CommercialSite.Web.UI/Areas/User/Controllers/OrderInfoController.cs
using AutoMapper;
using CommercialSite.Common.DTOs.OrderInfo;
using CommercialSite.Web.UI.APIs;
using CommercialSite.Web.UI.Areas.User.Models.OrderInfoViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using CommercialSite.Web.UI.Areas.User.Models.ShipmentInfoViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using CommercialSite.Web.UI.Areas.User.Models.OrderViewModels;
using CommercialSite.Web.UI.Models;
using CommercialSite.Common.DTOs.Order;

namespace CommercialSite.Web.UI.Areas.User.Controllers
{
    [Area("User"), Authorize]
    public class OrderInfoController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IShipmentInfoApi _shipmentInfoApi;
        private readonly IOrderInfoApi _orderInfoApi;
        private readonly IOrderApi _orderApi;
        private readonly IUserApi _userApi;
        private readonly IMapper _mapper;
        public OrderInfoController(
            IWebHostEnvironment env,
            IShipmentInfoApi shipmentInfoApi,
            IOrderInfoApi orderInfoApi,
            IOrderApi orderApi,
            IUserApi userApi,
            IMapper mapper)
        {
            _env = env;
            _shipmentInfoApi = shipmentInfoApi;
            _orderInfoApi = orderInfoApi;
            _orderApi = orderApi;
            _userApi = userApi;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<ShipmentInfoViewModel> listC = new List<ShipmentInfoViewModel>();
            var listResultC = await _shipmentInfoApi.List();
            if (listResultC.IsSuccessStatusCode && listResultC.Content.IsSuccess && listResultC.Content.ResultData.Any())
                listC = _mapper.Map<List<ShipmentInfoViewModel>>(listResultC.Content.ResultData);
            ViewBag.ShipmentInfos = new SelectList(listC, "Id", "ShipmentName");
            return View();
        }

        public async Task<IActionResult> Insert(CreateOrderInfoViewModel item)
        {
             
            var userId = JsonConvert.DeserializeObject<Guid>(HttpContext.Session.GetString("UserId"));
            item.UserId = userId;

            if (ModelState.IsValid)
            {
                var insertResult = await _orderInfoApi.Post(_mapper.Map<OrderInfoRequest>(item));
                if (insertResult.IsSuccessStatusCode && insertResult.Content.IsSuccess && insertResult?.Content?.ResultData != null)
                {
                    var sessionCart = JsonConvert.DeserializeObject<List<ProductVM>>(HttpContext.Session.GetString("SessionCart"));
                    for (int i = 0; i < sessionCart.Count(); i++)
                    {
                        CreateOrderViewModel orderVM = new CreateOrderViewModel()
                        {
                            OrderInfoId = insertResult.Content.ResultData.Id,
                            ProductId = sessionCart.Select(x => x.Id).ToList()[i],
                            UserId = userId,
                            Status = Common.Enums.Status.Active
                        };

                        var insertOrder = await _orderApi.Post(_mapper.Map<OrderRequest>(orderVM));
                    }
                    HttpContext.Session.Remove("SessionCart");
                    return RedirectToAction("Index", "Home", new { area = "" });
                }
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";

            }
            else
                TempData["Message"] = "İşlem başarısız oldu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            return View(item);
        }
    }
}

CommercialSite/CommercialSite.Web.UI/Controllers/ProductDetailController.cs
using AutoMapper;
using CommercialSite.Web.UI.APIs;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialSite.Web.UI.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly IProductApi _productApi;
        private readonly IMapper _mapper;
        private readonly IProductImageApi _productImageApi;

        public ProductDetailController(
            IProductApi productApi,
            IProductImageApi productImageApi,
            IMapper mapper)
        {
            _productApi = productApi;
            _mapper = mapper;
            _productImageApi = productImageApi;
        }

       public async Task<ActionResult> Index(string name, Guid id)
       {
           //List<Product> vm = db.Products.Where(x => x.Id == id).ToList();
           if (id == null)
           {
               List<ProductViewModel> listProduct = new List<ProductViewModel>();
               var listProductResult = await _productApi.List();
                if (listProductResult.IsSuccessStatusCode && listProductResult.Content.IsSuccess && listProductResult.Content.ResultData.Any())
                    
                   listProduct = _mapper.Map<List<ProductViewModel>>(listProductResult.Content.ResultData.ToList());

               return View("~/Views/Home/Index.cshtml", listProduct);
           }
           else
           {
               List<ProductViewModel> listProduct = new List<ProductViewModel>();
               var listProductResult = await _productApi.List();
               if (listProductResult.IsSuccessStatusCode && listProductResult.Content.IsSuccess)
                   listProduct = _mapper.Map<List<ProductViewModel>>(listProductResult.Content.ResultData.Where(x=>x.Id == id).ToList());
               //Product productVM = productRepository.SelectById(id.Value);
               return View(listProduct);
           }
       }
    }
}

CommercialSite/CommercialSite.Web.UI/Controllers/ProductListController.cs
using AutoMapper;
using CommercialSite.Web.UI.APIs;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductPropertyViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialSite.Web.UI.Controllers
{
    public class ProductListController : Controller
    {
        private readonly IProductApi _productApi;
        private readonly IProductPropertyApi _productPropertyApi;
        private readonly IMapper _mapper;

        public ProductListController(
            IProductApi productApi,
            IProductPropertyApi productPropertyApi,
            IMapper mapper)
        {
            _productApi = productApi;
            _productPropertyApi = productPropertyApi;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index(string name)
        {
            List<ProductViewModel> listProduct = new List<ProductViewModel>();
            var listProductResult = await _productApi.List();
            if (listProductResult.IsSuccessStatusCode && listProductResult.Content.IsSuccess && listProductResult.Content.ResultData.Where(x=>x.Brand.BrandName.ToLower() == name.ToLower()).Any())
                listProduct = _mapper.Map<List<ProductViewModel>>(listProductResult.Content.ResultData.Where(x=>x.Brand.BrandName.ToLower() == name.ToLower()).ToList());

            else if (listProductResult.IsSuccessStatusCode && listProductResult.Content.IsSuccess && listProductResult.Content.ResultData.Where(x => x.Category.CategoryName.ToLower() == name.ToLower()).Any())
                listProduct = _mapper.Map<List<ProductViewModel>>(listProductResult.Content.ResultData.Where(x => x.Category.CategoryName.ToLower() == name.ToLower()).ToList());

            return View(listProduct);
        }
    }
}

CommercialSite/CommercialSite.Web.UI/Controllers/ShoppingCartController.cs
using CommercialSite.Web.UI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialSite.Web.UI.Controllers
{
    public class ShoppingCartController : Controller
    {
        public IActionResult List()
        {
            if (HttpContext.Session.Keys.Contains("SessionCart"))
            {
                var sessionCart = JsonConvert.DeserializeObject<List<ProductVM>>(HttpContext.Session.GetString("SessionCart"));
                List<ProductVM> throwTheNulls = new List<ProductVM>();
                foreach (var item in sessionCart)
                {
                    if (item.CategoryName != null)
                    {
                        throwTheNulls.Add(item);
                    }
                }
                return View("Index", throwTheNulls);
            }
            ;
            return View("Index");
        }
        
        public IActionResult Add(Guid id,Guid userId, string productName, string categoryName, string brandName, double withoutDiscountPrice, double discountPrice, int rate, string imageUrl)
        {
            ProductVM vm = new ProductVM()
            {
                Id = id,
                ProductName = productName,
                Image = imageUrl,
                TotalPrice = withoutDiscountPrice,
                TrullyPrice = discountPrice,
                CategoryName = categoryName,
                Rates = rate,
                Quantity = 1,
                BrandName = brandName,
                UserId = userId
            };

            List<ProductVM> vmList = new List<ProductVM>();

            if (HttpContext.Session.Keys.Contains("SessionCart"))
            {
                var sessionCartControl = JsonConvert.DeserializeObject<List<ProductVM>>(HttpContext.Session.GetString("SessionCart"));
                if (sessionCartControl.Where(x => x.Id == vm.Id).Any() && vm.CategoryName != null)
                {
                    foreach (var item in sessionCartControl)
                    {
                        if (vm.Id == item.Id)
                        {
                            item.Quantity++;
                            break;
                        }
                    }
                }
                else
                    vmList.Add(vm);
                vmList.AddRange(sessionCartControl);
                vmList.RemoveAll(x => x.CategoryName == null);
                HttpContext.Session.SetString("SessionCart", JsonConvert.SerializeObject(vmList));
                return RedirectToAction("Index", "Home");
            }
            else
            {
                vmList.Add(vm);
                HttpContext.Session.SetString("SessionCart", JsonConvert.SerializeObject(vmList));
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Increase(Guid id)
        {
            var sessionCartControl = JsonConvert.DeserializeObject<List<ProductVM>>(HttpContext.Session.GetString("SessionCart"));


            foreach (var item in sessionCartControl)
            {
                if (id == item.Id)
                {
                    item.Quantity++;
                    break;
                }
            }
            HttpContext.Session.SetString("SessionCart", JsonConvert.SerializeObject(sessionCartControl));
            return RedirectToAction("List", "ShoppingCart");
        }

        public IActionResult Decrease(Guid id)
        {
            var sessionCartControl = JsonConvert.DeserializeObject<List<ProductVM>>(HttpContext.Session.GetString("SessionCart"));

            foreach (var item in sessionCartControl)
            {
                if (id == item.Id)
                {
                    if (item.Quantity == 1)
                    {
                        sessionCartControl.RemoveAll(x => x.Id == id);
                        RedirectToAction("Remove", "ShoppingCart");
                    }
                    item.Quantity--;
                    break;
                }
            }
            HttpContext.Session.SetString("SessionCart", JsonConvert.SerializeObject(sessionCartControl));
            return RedirectToAction("List", "ShoppingCart");
        }

        public IActionResult Remove(Guid id)
        {
            var sessionCartControl = JsonConvert.DeserializeObject<List<ProductVM>>(HttpContext.Session.GetString("SessionCart"));

            sessionCartControl.RemoveAll(x => x.Id == id);

            HttpContext.Session.SetString("SessionCart", JsonConvert.SerializeObject(sessionCartControl));

            return RedirectToAction("List", "ShoppingCart");
        }

        public IActionResult Finished()
        {
            HttpContext.Session.Remove("SessionCart");

            return View("Finished");
        }
    }
}

CommercialSite/CommercialSite.Web.UI/Views/ShoppingCart/Finished.cshtml
@{
    ViewBag.Title = "Finished";
}
<div class="container" style="padding:100px 0 100px 0;">
    <div class="row">
        <div class="col-lg-2">

        </div>
        <div class="col-lg-8">
            <h2>Tebrikler Siparişiniz Başarıyla Gerçekleştirilmiştir.</h2>
            <div class="row" style="padding-top:50px;">
                <div class="col-lg-5">

                </div>
                <div class="col-lg-2">
                    <a asp-action="Index" asp-controller="Home" class="justify-content-center">Anasayfaya</a>
                </div>
                <div class="col-lg-5">

                </div>
            </div>
           
        </div>
        <div class="col-lg-2">

        </div>
    </div>
</div>

CommercialSite/CommercialSite.Web.UI/Views/ShoppingCart/Index.cshtml
@model IEnumerable<ProductVM>
@{
    ViewBag.Title = "Index";
}
<link href="~/Content/my-css/ShoppingCart.css" rel="stylesheet" />
<script src="~/Content/jquery/jquery.js"></script>

@if (Model != null)
{
    double? withOutDiscountPrice = 0;
    double? discountPrice = 0;
    double? totalDiscount = 0;

    <div class="container-fluid ml-lg-5 mt-lg-5 mb-lg-5">
        <div class="row ml-lg-5 mr-lg-5">
            <div class="col-lg-8 mr-5 hat-cek throw-product">

                <div class="row alt-hat">
                    <h3 class="ml-lg-5 mb-lg-4 mt-3">Sepetim<span class="bi bi-arrow-down-short ml-2"></span> <small class="ml-3">@Model.Count() Ürün</small></h3>
                </div>
                @foreach (var item in Model)
                        {
                            withOutDiscountPrice += item.TotalPrice * item.Quantity;
                            discountPrice += item.TrullyPrice  * item.Quantity;
                            totalDiscount = withOutDiscountPrice - discountPrice;
        
                            <div class="row mt-3 productList">
                        <div class="col-lg-2 mr-2 ml-2">
                            <a asp-controller="ProductDetail" asp-action="Index" asp-route-id="@item.Id">
                                <img class="img-fluid" src="@Url.Content($"~/Upload/ProductImages/{item.Image}")" alt="@item.Image">
                            </a>
                        </div>
                        <div class="col-lg-7 mr-lg-3">
                            <h6><a asp-controller="ProductDetail" asp-action="Index" asp-route-id="@item.Id" class="none-underline link-primary"><b>@item.ProductName</b></a></h6>
                            <div class="row mt-3">
                                <div class="col-lg-3">
                                    <p class="text-center"><a asp-controller="ProductList" asp-action="Index" asp-route-name="@item.BrandName" class="none-underline link-default">@item.BrandName</a></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-5 ml-5 ">
                                    <h4 class="price">@item.TrullyPrice.ToString() TL</h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="row ">
                                <div class="col-lg-4 ml-4 mt-4">
                                    <a asp-controller="FavoriteProduct" asp-action="Add" asp-route-productId="@item.Id" asp-area="User"><span class="bi bi-heart" data-toggle="Favori Listeme Ekle" title="Ürünü Favori Listeme Ekle" data-placement="right"><small class="wish-cart"></small></span></a>

                                    <a asp-controller="ShoppingCart" asp-action="Remove" asp-route-id="@item.Id"><span class="bi bi-trash" data-toggle="tooltip" title="Ürünü Sepetten Kaldır" data-placement="right"></span></a>
                                </div>

                                <div class="col-lg-2  ml-lg-3">

                                    <a asp-controller="ShoppingCart" asp-action="Increase" asp-route-id="@item.Id" class="positive mb-lg-2 none-underline" style="color:forestgreen;" data-toggle="tooltip" title="Miktarı Arttır" data-placement="right">+</a>

                                    <h6 style="padding-top: 10px; padding-left:6px;">@item.Quantity</h6>

                                    <a asp-controller="ShoppingCart" asp-action="Decrease" asp-route-id="@item.Id" class="positive mb-lg-2 none-underline" style="color:red" data-toggle="tooltip" title="Miktarı Azalt" data-placement="right">-</a>

                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="hat-cek"></p>
                }  
            </div>
            <div class="col-lg-3 ">
                <div class="hat-cek">
                    <div class="row">
                        <div class="col-lg-12">
                            <h4 class="mt-4 ml-3" style="color:#808080">Ödenecek Tutar</h4>
                            <h4 class="text-center price mt-4 trullyPrice">@discountPrice TL</h4>
                        </div>
                    </div>
                    <div class="row  mt-3 total-price">
                        <h6 class="float-left ml-lg-3 reserve-place-3">Toplam Tutar :</h6>
                        <h6 class="float-left reserve-place-4 totalPrice">@withOutDiscountPrice TL</h6>
                    </div>
                    <div class="row  mt-3 discount-price">
                        <h6 class="float-left ml-lg-3 reserve-place-3">İndirim :</h6>
                        <h6 class="float-left reserve-place-4 outDiscount">@totalDiscount TL</h6>
                    </div>
                    <div class="text-center mt-lg-3 alt-hat">
                        <a asp-action="Index" asp-controller="OrderInfo" asp-area="User" class="btn btn-cart">Devam Et</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
	{
<div class="container-fluid ml-lg-5 mt-lg-5 mb-lg-5">
    <div class="row ml-lg-5 mr-lg-5">
        <div class="col-lg-8 mr-5 hat-cek throw-product">
            <div class="row alt-hat">
                <h3 class="ml-lg-5 mb-lg-4 mt-3">Sepetim<span class="bi bi-arrow-down-short ml-2"></span> <small class="ml-3">0 Ürün</small></h3>
            </div>
            <h1>Sepetinizde ürün bulunmamaktadır.</h1>
        </div>
        <div class="col-lg-3 ">
            <div class="hat-cek">
                <div class="row">
                    <div class="col-lg-12">
                        <h4 class="mt-4 ml-3" style="color:#808080">Ödenecek Tutar</h4>
                        <h4 class="text-center price mt-4 trullyPrice">0.00 TL</h4>
                    </div>
                </div>
                <div class="row  mt-3 total-price">
                    <h6 class="float-left ml-lg-3 reserve-place-3">Toplam Tutar :</h6>
                    <h6 class="float-left reserve-place-4 totalPrice">0.00 TL</h6>
                </div>
                <div class="row  mt-3 discount-price">
                    <h6 class="float-left ml-lg-3 reserve-place-3">İndirim :</h6>
                    <h6 class="float-left reserve-place-4 outDiscount">0.00 TL</h6>
                </div>
                <div class="row  mt-3 shipping-price">
                    @*<h6 class="float-left ml-lg-3 reserve-place-3">Kargo :</h6>
                        <h6 class="float-left reserve-place-4">0.00 TL</h6>*@
                </div>
                <div class="text-center mt-lg-3 alt-hat">
                    <button type="button" class="btn btn-cart">Alışverişi Tamamla</button>
                </div>
            </div>
        </div>
    </div>
</div> 
	}