CommercialSite/CommercialSite.Web.UI/Areas/Admin/Models/ProductImageViewModels/ProductImageViewModel.cs
using CommercialSite.Common.Enums;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductDetailViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CommercialSite.Web.UI.Areas.Admin.Models.ProductImageViewModels
{
    public class ProductImageViewModel
    {
        public ProductImageViewModel()
        {
            ProductDetails = new HashSet<ProductDetailViewModel>();
        }
        public Guid Id { get; set; }
        public Guid ProductId { get; set; }
        public ProductViewModel Product { get; set; }
        public string ImageUrl { get; set; }
        public Status Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public ICollection<ProductDetailViewModel> ProductDetails { get; set; }

    }
}

CommercialSite/CommercialSite.Web.UI/Areas/Admin/Controllers/ProductImageController.cs
using AutoMapper;
using CommercialSite.Common.DTOs.ProductImage;
using CommercialSite.Web.UI.APIs;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductImageViewModels;
using CommercialSite.Web.UI.Areas.Admin.Models.ProductViewModels;
using CommercialSite.Web.UI.Infrastructure.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CommercialSite.Web.UI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class ProductImageController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IProductImageApi _productImageApi;
        private readonly IProductApi _productApi;
        private readonly IMapper _mapper;
        public ProductImageController(
            IWebHostEnvironment env,
            IProductImageApi productImageApi,
            IProductApi productApi,
            IMapper mapper)
        {
            _env = env;
            _productImageApi = productImageApi;
            _productApi = productApi;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<ProductImageViewModel> list = new List<ProductImageViewModel>();
            var listResult = await _productImageApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductImageViewModel>>(listResult.Content.ResultData);
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> Insert()
        {
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            ViewBag.Products = new SelectList(list, "Id", "ProductName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Insert(CreateProductImageViewModel item, List<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                bool imageResult;
                string imagePath = Upload.ImageUpload(files, _env, out imageResult);
                if (imageResult)
                    item.ImageUrl = imagePath;
                else
                {
                    ViewBag.Message = imagePath;
                    return View();
                }
                
                var insertResult = await _productImageApi.Post(_mapper.Map<ProductImageRequest>(item));
                if (insertResult.IsSuccessStatusCode && insertResult.Content.IsSuccess && insertResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";

            }
            else
                TempData["Message"] = "İşlem başarısız oldu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            List<ProductViewModel> list = new List<ProductViewModel>();
            var listResult = await _productApi.List();
            if (listResult.IsSuccessStatusCode && listResult.Content.IsSuccess && listResult.Content.ResultData.Any())
                list = _mapper.Map<List<ProductViewModel>>(listResult.Content.ResultData);
            ViewBag.Products = new SelectList(list, "Id", "ProductName");

            UpdateProductImageViewModel model = new UpdateProductImageViewModel();
            var updateModelResult = await _productImageApi.Get(id);
            if (updateModelResult.IsSuccessStatusCode && updateModelResult.Content.IsSuccess && updateModelResult?.Content?.ResultData != null)
                model = _mapper.Map<UpdateProductImageViewModel>(updateModelResult?.Content?.ResultData);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateProductImageViewModel item)
        {
            if (ModelState.IsValid)
            {

                var updateResult = await _productImageApi.Put(item.Id, _mapper.Map<ProductImageRequest>(item));
                if (updateResult.IsSuccessStatusCode && updateResult.Content.IsSuccess && updateResult?.Content?.ResultData != null)
                    return RedirectToAction("Index");
                else
                    TempData["Message"] = "Kayıt işlemi sırasında bir hata oluştu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            }
            else
                TempData["Message"] = "İşlem başarısız oldu!...Lütfen Tüm alanları kontrol edip tekrar deneyiniz...";
            return View(item);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var deleteResult = await _productImageApi.Delete(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Activate(Guid id)
        {
            var deleteResult = await _productImageApi.Activate(id);
            return RedirectToAction("Index");
        }
    }
}

CommercialSite/CommercialSite.Web.UI/Areas/Admin/Views/ProductImage/Index.cshtml
@model List<ProductImageViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_YöneticiLayout.cshtml";
}

<div class="content-body">
    <div class="row justify-content-between align-items-center mb-10">
        <div class="col-12 col-lg-auto mb-20">
            <div class="page-heading">
                <h3 class="title">List <span>/ ProductImages</span></h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-30">
            <div class="box">
                <div class="box-head">
                    <a asp-controller="ProductImage" asp-action="Insert" class="btn btn-primary">Yeni Kayıt</a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered data-table data-table-default">
                        <thead>
                            <tr>
                                <th>ImageUrl</th>
                                <th>Created Date</th>
                                <th>Status</th>
                                <th>####</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (ProductImageViewModel item in Model)
                            {
                                <tr>
                                    <td>@item.ImageUrl</td>
                                    <td>@item.CreatedDate</td>
                                    <td><partial name="PartialViews/_StatusPartial" model="item.Status" /></td>
                                    <td>
                                        <a asp-controller="ProductImage" asp-action="Activate" asp-route-id="@item.Id" class="btn">Activate</a>
                                        <a asp-controller="ProductImage" asp-action="Delete" asp-route-id="@item.Id" class="btn">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/admin/assets/js/plugins/datatables/datatables.min.js"></script>
    <script src="~/admin/assets/js/plugins/datatables/datatables.active.js"></script>
}

CommercialSite/CommercialSite.Web.UI/Areas/Admin/Views/ProductImage/Insert.cshtml
@model CreateProductImageViewModel
@{
    ViewData["Title"] = "Insert";
    Layout = "~/Areas/Admin/Views/Shared/_YöneticiLayout.cshtml";
}

<div class="content-body">
    <div class="row justify-content-between align-items-center mb-10">
        <div class="col-12 col-lg-auto mb-20">
            <div class="page-heading">
                <h3>Blog <span>/ Add</span></h3>
            </div>
        </div>
    </div>
    <div class="add-edit-product-wrap col-12">
        <div class="add-edit-product-form">
            <form asp-controller="ProductImage" asp-action="Insert" method="post" enctype="multipart/form-data">
                <h4 class="title">About ProductImage</h4>
                <div class="row">
                    <div class="col-lg-12 col-12 mb-30">
                        <input class="form-control" type="file" name="files">
                    </div>
                    <br />
                    <div class="col-lg-12 col-12 mb-30">
                        <select asp-for="ProductId" asp-items="@ViewBag.Products" class="form-control">
                            <option>Please select Product..</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="d-flex flex-wrap justify-content-end col mbn-10">
                        <button class="button button-outline button-primary mb-10 ml-10 mr-0">Save</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["Message"]
        </div>
    }
</div>

@section scripts{
    <script src="~/admin/assets/js/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="~/admin/assets/js/plugins/summernote/summernote.active.js"></script>
    <script src="~/admin/assets/js/plugins/quill/quill.min.js"></script>
    <script src="~/admin/assets/js/plugins/quill/quill.active.js"></script>
}